export let ryanMockData = [
    {
        outbound: {
            departureAirport: {
                countryName: "United Kingdom",
                iataCode: "BRS",
                name: "Bristol",
                seoName: "bristol",
                city: {
                    name: "Bristol",
                    code: "BRISTOL",
                    countryCode: "gb",
                },
            },
            arrivalAirport: {
                countryName: "Spain",
                iataCode: "ACE",
                name: "Lanzarote",
                seoName: "lanzarote",
                city: {
                    name: "Lanzarote",
                    code: "LANZAROTE",
                    countryCode: "es",
                },
            },
            departureDate: "2024-02-28T15:00:00",
            arrivalDate: "2024-02-28T18:55:00",
            price: {
                value: 17.99,
                valueMainUnit: "17",
                valueFractionalUnit: "99",
                currencyCode: "GBP",
                currencySymbol: "£",
            },
            flightKey: "FR~4755~ ~~BRS~02/28/2024 15:00~ACE~02/28/2024 18:55~~",
            flightNumber: "FR4755",
            previousPrice: null,
            priceUpdated: 1708245912000,
        },
        summary: {
            price: {
                value: 17.99,
                valueMainUnit: "17",
                valueFractionalUnit: "99",
                currencyCode: "GBP",
                currencySymbol: "£",
            },
            previousPrice: null,
            newRoute: false,
        },
    },
    {
        outbound: {
            departureAirport: {
                countryName: "United Kingdom",
                iataCode: "BRS",
                name: "Bristol",
                seoName: "bristol",
                city: {
                    name: "Bristol",
                    code: "BRISTOL",
                    countryCode: "gb",
                },
            },
            arrivalAirport: {
                countryName: "Spain",
                iataCode: "AGP",
                name: "Malaga",
                seoName: "malaga",
                city: {
                    name: "Malaga",
                    code: "MALAGA",
                    countryCode: "es",
                },
            },
            departureDate: "2024-04-11T21:10:00",
            arrivalDate: "2024-04-12T00:50:00",
            price: {
                value: 23.81,
                valueMainUnit: "23",
                valueFractionalUnit: "81",
                currencyCode: "GBP",
                currencySymbol: "£",
            },
            flightKey: "FR~4121~ ~~BRS~04/11/2024 21:10~AGP~04/12/2024 00:50~~",
            flightNumber: "FR4121",
            previousPrice: null,
            priceUpdated: 1708238511000,
        },
        summary: {
            price: {
                value: 23.81,
                valueMainUnit: "23",
                valueFractionalUnit: "81",
                currencyCode: "GBP",
                currencySymbol: "£",
            },
            previousPrice: null,
            newRoute: false,
        },
    },
    {
        outbound: {
            departureAirport: {
                countryName: "United Kingdom",
                iataCode: "BRS",
                name: "Bristol",
                seoName: "bristol",
                city: {
                    name: "Bristol",
                    code: "BRISTOL",
                    countryCode: "gb",
                },
            },
            arrivalAirport: {
                countryName: "Portugal",
                iataCode: "FAO",
                name: "Faro",
                seoName: "faro",
                city: {
                    name: "Faro",
                    code: "FARO",
                    countryCode: "pt",
                },
            },
            departureDate: "2024-03-03T06:30:00",
            arrivalDate: "2024-03-03T09:10:00",
            price: {
                value: 16.99,
                valueMainUnit: "16",
                valueFractionalUnit: "99",
                currencyCode: "GBP",
                currencySymbol: "£",
            },
            flightKey: "FR~4147~ ~~BRS~03/03/2024 06:30~FAO~03/03/2024 09:10~~",
            flightNumber: "FR4147",
            previousPrice: null,
            priceUpdated: 1708246039000,
        },
        summary: {
            price: {
                value: 16.99,
                valueMainUnit: "16",
                valueFractionalUnit: "99",
                currencyCode: "GBP",
                currencySymbol: "£",
            },
            previousPrice: null,
            newRoute: false,
        },
    },
    {
        outbound: {
            departureAirport: {
                countryName: "United Kingdom",
                iataCode: "BRS",
                name: "Bristol",
                seoName: "bristol",
                city: {
                    name: "Bristol",
                    code: "BRISTOL",
                    countryCode: "gb",
                },
            },
            arrivalAirport: {
                countryName: "Spain",
                iataCode: "LPA",
                name: "Gran Canaria",
                seoName: "gran-canaria",
                city: {
                    name: "Gran Canaria",
                    code: "GRAN_CANARIA",
                    countryCode: "es",
                },
            },
            departureDate: "2024-03-11T13:05:00",
            arrivalDate: "2024-03-11T17:15:00",
            price: {
                value: 19.99,
                valueMainUnit: "19",
                valueFractionalUnit: "99",
                currencyCode: "GBP",
                currencySymbol: "£",
            },
            flightKey: "FR~4757~ ~~BRS~03/11/2024 13:05~LPA~03/11/2024 17:15~~",
            flightNumber: "FR4757",
            previousPrice: null,
            priceUpdated: 1708238677000,
        },
        summary: {
            price: {
                value: 19.99,
                valueMainUnit: "19",
                valueFractionalUnit: "99",
                currencyCode: "GBP",
                currencySymbol: "£",
            },
            previousPrice: null,
            newRoute: false,
        },
    },
    {
        outbound: {
            departureAirport: {
                countryName: "United Kingdom",
                iataCode: "BRS",
                name: "Bristol",
                seoName: "bristol",
                city: {
                    name: "Bristol",
                    code: "BRISTOL",
                    countryCode: "gb",
                },
            },
            arrivalAirport: {
                countryName: "Spain",
                iataCode: "TFS",
                name: "Tenerife South",
                seoName: "tenerife-south",
                city: {
                    name: "Tenerife",
                    code: "TENERIFE",
                    macCode: "TEN",
                    countryCode: "es",
                },
            },
            departureDate: "2024-03-10T13:15:00",
            arrivalDate: "2024-03-10T17:25:00",
            price: {
                value: 21.99,
                valueMainUnit: "21",
                valueFractionalUnit: "99",
                currencyCode: "GBP",
                currencySymbol: "£",
            },
            flightKey: "FR~4753~ ~~BRS~03/10/2024 13:15~TFS~03/10/2024 17:25~~",
            flightNumber: "FR4753",
            previousPrice: null,
            priceUpdated: 1708246899000,
        },
        summary: {
            price: {
                value: 21.99,
                valueMainUnit: "21",
                valueFractionalUnit: "99",
                currencyCode: "GBP",
                currencySymbol: "£",
            },
            previousPrice: null,
            newRoute: false,
        },
    },
];